Exclude:
  - .faker

Locale:
  AR:
    Enabled: false
  AZ:
    Enabled: false
  BG:
    Enabled: false
  BS:
    Enabled: false
  CA:
    Enabled: false
  CS:
    Enabled: false
  DA:
    Enabled: false
  DE:
    Enabled: false
  EE:
    Enabled: false
  EN:
    Enabled: false
  EL:
    Enabled: false
  EO:
    Enabled: false
  ES:
    Enabled: false
  FA:
    Enabled: false
  FI:
    Enabled: false
  FR:
    Enabled: false
  HE:
    Enabled: false
  HR:
    Enabled: false
  HU:
    Enabled: false
  HY:
    Enabled: false
  ID:
    Enabled: false
  IT:
    Enabled: false
  JA:
    Enabled: false
  KO:
    Enabled: false
  LT:
    Enabled: false
  LV:
    Enabled: false
  MK:
    Enabled: false
  NB:
    Enabled: false
  NL:
    Enabled: false
  PL:
    Enabled: false
  PT:
    Enabled: false
  RO:
    Enabled: false
  SK:
    Enabled: false
  SV:
    Enabled: false
  TH:
    Enabled: false
  TR:
    Enabled: false
  UK:
    Enabled: false
  VI:
    Enabled: false
  "CA-CA":
    Enabled: false
  "DA-DK":
    Enabled: false
  "DE-AT":
    Enabled: false
  "DE-CH":
    Enabled: false
  "EN-AU":
    Enabled: false
  "EN-AU":
    Enabled: false
  "EN-BO":
    Enabled: false
  "EN-CA":
    Enabled: false
  "EN-GB":
    Enabled: false
  "EN-IN":
    Enabled: false
  "EN-MS":
    Enabled: false
  "EN-NE":
    Enabled: false
  "EN-NG":
    Enabled: false
  "EN-NZ":
    Enabled: false
  "EN-PA":
    Enabled: false
  "EN-SG":
    Enabled: false
  "EN-TH":
    Enabled: false
  "EN-UG":
    Enabled: false
  "EN-US":
    Enabled: false
  "EN-ZA":
    Enabled: false
  "ES-MX":
    Enabled: false
  "FI-FI":
    Enabled: false
  "FR-CA":
    Enabled: false
  "FR-CH":
    Enabled: false
  "NB-NO":
    Enabled: false
  "NO-NO":
    Enabled: false
  "PT-BR":
    Enabled: false
  "PT-PT":
    Enabled: false
  "SV-SE":
    Enabled: false
  "ZH-CN":
    Enabled: false
  "ZH-TW":
    Enabled: false
  "ca-CAT":
    Enabled: false
  "en-au":
    Enabled: false
  "en-BORK":
    Enabled: false
  "en-IND":
    Enabled: false
  "en-NEP":
    Enabled: false
  "en-PAK":
    Enabled: false
  "en-au-ocker":
    Enabled: false
