# This file was generated by rails_favicon_generator, from
# https://realfavicongenerator.net/

# It makes files with .webmanifest extension first class files in the asset
# pipeline. This is to preserve this extension, as is it referenced in a call
# to asset_path in the _favicon.html.erb partial.

Rails.application.config.assets.configure do |env|

  sprockets_v4 = Sprockets::VERSION.split('.').first.to_i >= 4

  mime_types = [
    [".webmanifest", "application/manifest+json" ],
    [".xml",         "application/xml"           ]
  ]

  mime_types.each do |extension, mime_type|
    env.register_mime_type    mime_type, extensions: [extension, "#{extension}.erb"]
    env.register_preprocessor(mime_type, Sprockets::ERBProcessor) if sprockets_v4
  end
end
