# This file was generated by rails_favicon_generator, from
# https://realfavicongenerator.net/

# It makes files with .webmanifest extension first class files in the asset
# pipeline. This is to preserve this extension, as is it referenced in a call
# to asset_path in the _favicon.html.erb partial.

Rails.application.config.assets.configure do |env|
  sprockets_v4 = Sprockets::VERSION.split('.').first.to_i >= 4

  mime_types = [
    { ext: ".webmanifest", mime: "application/manifest+json" },
    { ext: ".xml",         mime: "application/xml" }
  ]

  mime_types.each do |type|
    env.register_mime_type    type[:mime], extensions: [type[:ext], "#{type[:ext]}.erb"]
    env.register_preprocessor(type[:mime], Sprockets::ERBProcessor) if sprockets_v4
  end
end
