<% project_name = "my_project_name_ru" %>

default: &default
  adapter: mysql
  encoding: utf8
  # host: localhost # Heroku
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  socket: /tmp/mysql.sock
  username: root

development:
  <<: *default
  database: <%= project_name %>_development

test:
  <<: *default
  database: <%= project_name %>_test

production:
  <<: *default
  url: <%= ENV["JAWSDB_URL"] %>
