default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost # Heroku
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  # reaping_frequency: nil
  # socket: /tmp/.s.PGSQL.5432
  timeout: 5000
  username: <%= `whoami`.chomp %>

development:
  <<: *default
  database: project_name_development

test:
  <<: *default
  database: project_name_test

production:
  <<: *default
  database: project_name_production
  username: postgres
  # url: <%= ENV["DATABASE_URL"] %>
