<% project_name = "my_project_name_ru" %>

default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost # Heroku
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  # reaping_frequency: nil
  timeout: 5000
  username: <%= `whoami`.chomp %>

development:
  <<: *default
  database: <%= project_name %>_development

test:
  <<: *default
  database: <%= project_name %>_test

production:
  <<: *default
  database: <%= project_name %>_production
  username: postgres
