default: &default
  adapter: mysql2
  encoding: utf8
  # host: localhost # Heroku
  pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>
  port: 3306
  socket: /tmp/mysql.sock
  username: root

development:
  <<: *default
  database: project_name_development
  password: <%= ENV["MYSQL_PASSWORD"] %>

test:
  <<: *default
  database: project_name_test
  password: <%= ENV["MYSQL_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV["JAWSDB_URL"] %>
