default: &default
  adapter: mysql2
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4
  host: localhost
  # password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  socket: /tmp/mysql.sock
  timeout: 5000
  username: root

development:
  <<: *default
  database: project_name_development

test:
  <<: *default
  database: project_name_test

production:
  <<: *default
  url: <%= ENV["JAWSDB_URL"] %>
