# Configuration file for Sidekiq.
# Place this file at `config/sidekiq.yml` and Sidekiq will pick it up automatically.

# Options here can still be overridden by cmd line args.

# https://github.com/mperham/sidekiq/wiki/Active-Job#action-mailer
# https://github.com/mperham/sidekiq/wiki/Advanced-Options
# https://github.com/mperham/sidekiq/wiki/Advanced-Options#the-sidekiq-configuration-file
# https://github.com/mperham/sidekiq/blob/main/examples/config.yml

---
:concurrency: 2
:logfile: "log/sidekiq.log"
:pidfile: "tmp/pids/sidekiq.pid"
:queues:
  - ["default", 5]
  - ["mailers", 10]
